In [3]:
import os
import pandas as pd
import subprocess

In [14]:
p = subprocess.run("python ./target-runner.py 4 8 1101047833 yasmallbbob --name=hm --rotation=True --d=50 --budget=20   --solver=CMA-ES --scale=5.8196 --popsize_factor=5 --elitist=True --diagonal=False --fcmaes=True --random_init=False", stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')

In [17]:
p.replace('\r\n', '')

'2581.1621217457055'

In [13]:
out

b'2581.1621217457055\r\n'

In [2]:
os.system('python target-runner.py 4 8 1101047833 yasmallbbob --name=hm --rotation=True --d=50 --budget=20   --solver=CMA-ES --scale=5.8196 --popsize_factor=5 --elitist=True --diagonal=False --fcmaes=True --random_init=False')

0

In [19]:
df = pd.read_csv('./instances_small_10_50.txt', delimiter=' --', header=None)

C:\Users\Risto\.conda\envs\newEnv\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

In [20]:
df.columns = ['benchmark', 'funct', 'rot', 'dim', 'budg']

In [21]:
df

       benchmark                     funct             rot   dim       budg
0    yasmallbbob                   name=hm  rotation=False  d=10  budget=10
1    yasmallbbob            name=rastrigin  rotation=False  d=10  budget=10
2    yasmallbbob             name=griewank  rotation=False  d=10  budget=10
3    yasmallbbob           name=rosenbrock  rotation=False  d=10  budget=10
4    yasmallbbob               name=ackley  rotation=False  d=10  budget=10
..           ...                       ...             ...   ...        ...
259  yasmallbbob               name=discus   rotation=True  d=50  budget=40
260  yasmallbbob            name=bentcigar   rotation=True  d=50  budget=40
261  yasmallbbob     name=deceptiveillcond   rotation=True  d=50  budget=40
262  yasmallbbob  name=deceptivemultimodal   rotation=True  d=50  budget=40
263  yasmallbbob        name=deceptivepath   rotation=True  d=50  budget=40

[264 rows x 5 columns]

In [70]:
instances = []
for rec_index, rec in df.iterrows():
    instances.append(f'yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}')

In [55]:
df_output_new = df_output.copy()
df_output_new['instance'] = instances

In [63]:
df_rank = pd.read_csv('./output_with_ranks (1).csv', index_col=0)

In [71]:
instances = instances + ['', '']

In [75]:
new_df = df_rank.transpose()
new_df['instance'] = instances
new_df = new_df.transpose()

In [76]:
new_df.to_csv('output_with_rank.csv')

In [62]:
instances_series = pd.Series(instances)
instances_df = pd.DataFrame([instances_series])
pd.concat([df_rank, instances_df], ignore_index=True)

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,Unnamed: 0,best_count,mean_rank
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3,3,4,3,4,2,1,irace_1,58.0,2.526515
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,2,2,1,2,1,1,irace_2,137.0,1.958333
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5,3,5,5,5,5,3,irace_3,23.0,3.984848
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,3,3,2,3,4,2,irace_4,58.0,2.465909
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,4,1,3,2,default,114.0,2.174242
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,['default'],['default'],['default'],['irace_2'],['default'],['irace_2'],"['irace_1', 'irace_2']",best,NaN,NaN
6,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,python target-runner.py 4 8 1101047833 yasmall...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
irace_results_1 = []
for rec_index, rec in df.iterrows():
    p = subprocess.run(f'python target-runner.py 4 8 1101047833 yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}   --solver=CMA-ES --scale=0.4151 --popsize_factor=9 --elitist=False --diagonal=False --fcmaes=True --random_init=False', stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')
    p = p.replace('\r\n', '')
    print(p)
    irace_results_1.append(p)

22.406943478740345
81.59889814894407
1.0187110853622734
2271.008260648232
5.374355190033626
137.26114985990154
1.0
1180.3012515265714
10000.0
12.406967615901037
0.016927027678340867
0.01831563888873418
6687534.685521223
11542104.80533841
28308.208873645402
2845105.03060232
22026.465794806718
2657130.347614021
8273393.615647721
1.7316788453398182
1.0
1.0
22.34043666690072
105.41069977629047
0.8417664724377694
3030.3273453238107
5.758539514552755
162.46628658565345
1.0
567.1510329878034
10000.0
12.406967615901037
0.03338024710862664
0.049787068367863944
12106738.126104813
11185948.535499526
638923.3709071008
554972.1479791399
442413.3920089205
158166.89897414244
12547915.608195953
1.0
1.0
1.0
79.99327069465483
468.335395401798
0.9100299935942424
13709.177745132378
5.165822080042766
760.9866945319638
1.0
5721.745304423825
10000.0
46.74823924521799
3.702131732825619
2.718281828459045
43920217.6440778
46555515.59671838
1184651.858293221
3510165.679487862
442413.3920089205
831681.2334191169
45230727.15178981
1.2745609411844816
1.0
1.0
82.23711011120957
455.6138309491286
0.674246225024262
18681.38341072502
5.265233140770572
838.9725578121306
1.0
2238.6576781815893
10000.0
46.748239245217995
0.7010648798477197
1.0
46737810.00385826
46628798.232171185
3139582.258552938
1011692.2967243495
1202604.2841647768
5205.691054641259
58040951.00482491
0.8309759352100934
1.0
1.0
13.608014182280098
81.59889814894407
1.0187110853622734
1334.5363161411299
5.354567106590665
130.56164252761064
1.0
930.6998284069398
1493.8182691281947
8.27187884959604
0.016927027678340867
0.01831563888873418
4997433.533900298
7942804.362180648
28308.208873645402
2845105.03060232
22026.465794806718
2657130.347614021
5253973.72649163
1.7202445977143943
1.0
1.0
13.837763006911075
93.0482959979677
0.7653837338748428
2205.1094858109495
4.895177084662343
141.22305443335398
1.0
517.8227987001743
8715.089721090224
8.271878849596042
0.03338024710862664
0.049787068367863944
8192034.237052575
7647669.132622771
531190.4405626396
389905.09229832527
442413.3920089205
47773.51017582991
8561744.820601873
1.0
1.0
1.0
79.99327069465483
468.335395401798
0.8974436424982379
13709.177745132378
5.165822080042766
727.3842692254275
1.0
5161.961691891482
10000.0
46.74823924521799
3.702131732825619
2.718281828459045
43920217.6440778
46555515.59671838
1184651.858293221
2973871.1848339867
442413.3920089205
103204.61421088857
45230727.15178981
1.2745609411844816
1.0
1.0
82.23711011120957
455.6138309491286
0.674246225024262
18681.38341072502
5.244354003532642
782.0005449719365
1.0
2045.3976482593612
10000.0
46.748239245217995
0.7010648798477197
1.0
46737810.00385826
46628798.232171185
3139582.258552938
863415.6010255491
1202604.2841647768
5205.691054641259
58040951.00482491
0.610538602199638
1.0
1.0
13.608014182280098
74.5310497118108
1.0187110853622734
1334.5363161411299
5.354567106590665
130.56164252761064
1.0
930.6998284069398
1493.8182691281947
8.27187884959604
0.016927027678340867
0.01831563888873418
4997433.533900298
7942804.362180648
28308.208873645402
2845105.03060232
22026.465794806718
2657130.347614021
5253973.72649163
1.7202445977143943
1.0
1.0
13.837763006911075
93.0482959979677
0.7653837338748428
2205.1094858109495
4.895177084662343
127.72839986041359
1.0
517.8227987001743
8715.089721090224
8.271878849596042
0.03338024710862664
0.049787068367863944
8192034.237052575
7647669.132622771
531190.4405626396
389905.09229832527
442413.3920089205
47773.51017582991
8561744.820601873
1.0
1.0
1.0
69.63599611179704
468.335395401798
0.840961767314034
10513.0419063309
4.910108255271172
684.6678104254104
1.0
5099.755264017358
10000.0
41.463871801199275
2.867830104997547
2.718281828459045
39493927.367904834
41450763.20471792
876189.6057915394
2363426.129134261
442413.3920089205
103204.61421088857
43478400.76879222
1.070653930926978
1.0
1.0
71.73900875715414
455.6138309491286
0.674246225024262
16305.527590718728
5.011961920481479
782.0005449719365
1.0
1387.0161888261057
10000.0
41.46387180119927
0.04282890863252864
0.049787068367863944
40981063.30234496
40699693.763952546
2299134.028173944
618704.7010309625
1202604.2841647768
5205.691054641259
44893112.707854114
0.5463342246565385
1.0
1.0

In [25]:
default_output = []
for rec_index, rec in df.iterrows():
    cmd = f'python target-runner.py 4 8 1101047833 yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}   --solver=CMA-ES --scale=1 --popsize_factor=3 --elitist=False --diagonal=False --fcmaes=False --random_init=False'
    p = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')
    p = p.replace('\r\n', '')
    default_output.append(p)

In [11]:
df_output = pd.DataFrame({'irace_1':irace_results_1,
                          'default': default_output})

In [12]:
df_output.to_csv('./output.csv')

In [26]:
irace_results_2 = []
for rec_index, rec in df.iterrows():
    cmd = f'python target-runner.py 4 8 1101047833 yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}   --solver=CMA-ES --scale=0.3177 --popsize_factor=7 --elitist=False --diagonal=False --fcmaes=True --random_init=False'
    p = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')
    p = p.replace('\r\n', '')
    irace_results_2.append(p)

In [27]:
irace_results_3 = []
for rec_index, rec in df.iterrows():
    cmd = f'python target-runner.py 4 8 1101047833 yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}   --solver=CMA-ES --scale=6.1404 --popsize_factor=8 --elitist=True --diagonal=False --fcmaes=False --random_init=False'
    p = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')
    p = p.replace('\r\n', '')
    irace_results_3.append(p)

In [28]:
irace_results_4 = []
for rec_index, rec in df.iterrows():
    cmd = f'python target-runner.py 4 8 1101047833 yasmallbbob --{rec["funct"]} --{rec["rot"]} --{rec["dim"]} --{rec["budg"]}   --solver=CMA-ES --scale=0.4267 --popsize_factor=9 --elitist=False --diagonal=False --fcmaes=True --random_init=False'
    p = subprocess.run(cmd, stdout=subprocess.PIPE, shell=True).stdout.decode('utf-8')
    p = p.replace('\r\n', '')
    irace_results_4.append(p)

In [48]:
df_output = pd.DataFrame({'irace_1':irace_results_1,
                          'irace_2': irace_results_2,
                          'irace_3': irace_results_3,
                          'irace_4': irace_results_4,
                          'default': default_output})

In [30]:
df_output.to_csv('./output_all.csv')

In [49]:
df_output['irace_1'] = pd.to_numeric(df_output['irace_1'])
df_output['irace_2'] = pd.to_numeric(df_output['irace_2'])
df_output['irace_3'] = pd.to_numeric(df_output['irace_3'])
df_output['irace_4'] = pd.to_numeric(df_output['irace_4'])
df_output['default'] = pd.to_numeric(df_output['default'])

In [50]:
df_output['Min_Col']=df_output.iloc[:,:].idxmin(1)

In [52]:
df_output.to_csv('./output_with_min.csv')

In [51]:
import collections
collections.Counter(df_output['Min_Col'].values.tolist())

Counter({'irace_2': 109, 'irace_1': 58, 'default': 78, 'irace_4': 19})

In [53]:
109 + 58 + 19

186